# Generated by Django 4.1 on 2022-08-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancesveiculo',
            name='seu_lance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
