# Generated by Django 4.1 on 2022-08-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lances', '0003_lancesveiculo_final_lance_lancesveiculo_inicio_lance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancesveiculo',
            name='final_lance',
        ),
        migrations.RemoveField(
            model_name='lancesveiculo',
            name='inicio_lance',
        ),
    ]
