# Generated by Django 4.1 on 2022-08-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_veiculo', models.CharField(max_length=75, verbose_name='Nome')),
                ('marca_veiculo', models.CharField(max_length=75, verbose_name='Marca')),
                ('ano_veiculo', models.DateField()),
                ('preco_veiculo', models.CharField(max_length=155, verbose_name='Preco')),
                ('preco_tabela', models.CharField(max_length=155, verbose_name='Preco Tabela')),
                ('estado_veiculo', models.CharField(max_length=50, verbose_name='Estado veiculo')),
                ('descricao_curta_veiculo', models.CharField(max_length=50, verbose_name='Descricao')),
                ('descricao_veiculo', models.TextField(verbose_name='Descricao')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m', verbose_name='Imagem')),
                ('categoria_veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
