# Generated by Django 4.1 on 2022-08-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculos',
            options={'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
    ]
