# Generated by Django 4.1 on 2022-08-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0002_alter_veiculos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='final_lance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='inicio_lance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
